name: hello-world
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: checkout
      - uses: actions/checkout@v2
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .


  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download a Build Artifact
          uses: actions/download-artifact@v2
          with:
            name: code
            path: .
      - name: my-step
        run: chmod +x ci/build-app.sh && bash ci/build-app.sh
      - name: Upload a Build Artifact
          uses: actions/upload-artifact@v2
          with:
            name: code
            path: .  
    needs: Clone-down

  Test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download a Build Artifact
            uses: actions/download-artifact@v2
            with:
              name: code
              path: .
      - name: test-step
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
        
    needs: Clone-down

    