name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle6-jdk11
    steps:
      - name: my-step
      - uses: actions/checkout@2
        run: ci/build.app.sh chmod +x vi/build-app.sh