name: hello-world
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: my-step
        run: bash ci/build-app.sh

  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
    needs: Clone-down

  Test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: test-step
        run: ci/unit-test-app.sh
    needs: Clone-down

    