name: Java CI
on: push
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}        
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .


  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .  
      - name: Build a jar file
        run: chmod +x ci/build-app.sh && bash ci/build-app.sh
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-uf-artifact
          path: . 

    needs: Clone-down

  Test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: test-step
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh    
    needs: Clone-down

  Docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: code-uf-artifact
          path: .
      - name: docker build
        run: sh chmod +x ci/build-docker.sh && ci/build-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA"
      - name: docker build
        run: sh chmod +x ci/push-docker.sh && ci/push-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA"
    needs: [Build, Test]
    
  
    