name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: my-step
        run: bash ci/build-app.sh
      - name: test-step
        run: ci/unit-test-app.sh
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
      - name: workflow
        jobs:
          Clone-down: my-step
          Test: test-step
            needs: Clone-down
          Build: Upload a Build Artifact
            needs: Clone-down
